In [30]:
import pandas as pd
import numpy as np

In [31]:
df = pd.read_csv("../data/raw.csv")

/var/folders/25/q0z41q9517j4f731_v9b8b0c0000gn/T/ipykernel_68317/3992164491.py:1: DtypeWarning: Columns (0: Unnamed: 22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/raw.csv")

In [32]:
df.head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [33]:
df.shape

(128975, 24)

In [12]:
df.columns

Index(['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B', 'fulfilled-by', 'Unnamed: 22'],
      dtype='str')

In [35]:
df.info

<bound method DataFrame.info of          index             Order ID      Date                        Status  \
0            0  405-8078784-5731545  04-30-22                     Cancelled
1            1  171-9198151-1101146  04-30-22  Shipped - Delivered to Buyer
2            2  404-0687676-7273146  04-30-22                       Shipped
3            3  403-9615377-8133951  04-30-22                     Cancelled
4            4  407-1069790-7240320  04-30-22                       Shipped
...        ...                  ...       ...                           ...
128970  128970  406-6001380-7673107  05-31-22                       Shipped
128971  128971  402-9551604-7544318  05-31-22                       Shipped
128972  128972  407-9547469-3152358  05-31-22                       Shipped
128973  128973  402-6184140-0545956  05-31-22                       Shipped
128974  128974  408-7436540-8728312  05-31-22                       Shipped

       Fulfilment Sales Channel  ship-service-level    Style              SKU  \
0        Merchant      Amazon.in           Standard   SET389   SET389-KR-NP-S
1        Merchant      Amazon.in           Standard  JNE3781  JNE3781-KR-XXXL
2          Amazon      Amazon.in          Expedited  JNE3371    JNE3371-KR-XL
3        Merchant      Amazon.in           Standard    J0341       J0341-DR-L
4          Amazon      Amazon.in          Expedited  JNE3671  JNE3671-TU-XXXL
...           ...            ...                ...      ...              ...
128970     Amazon      Amazon.in          Expedited  JNE3697    JNE3697-KR-XL
128971     Amazon      Amazon.in          Expedited   SET401   SET401-KR-NP-M
128972     Amazon      Amazon.in          Expedited    J0157     J0157-DR-XXL
128973     Amazon      Amazon.in          Expedited    J0012     J0012-SKD-XS
128974     Amazon      Amazon.in          Expedited    J0003      J0003-SET-S

             Category  ... currency   Amount    ship-city    ship-state  \
0                 Set  ...      INR   647.62       MUMBAI   MAHARASHTRA
1               kurta  ...      INR   406.00    BENGALURU     KARNATAKA
2               kurta  ...      INR   329.00  NAVI MUMBAI   MAHARASHTRA
3       Western Dress  ...      INR   753.33   PUDUCHERRY    PUDUCHERRY
4                 Top  ...      INR   574.00      CHENNAI    TAMIL NADU
...               ...  ...      ...      ...          ...           ...
128970          kurta  ...      INR   517.00    HYDERABAD     TELANGANA
128971            Set  ...      INR   999.00     GURUGRAM       HARYANA
128972  Western Dress  ...      INR   690.00    HYDERABAD     TELANGANA
128973            Set  ...      INR  1199.00        Halol       Gujarat
128974            Set  ...      INR   696.00       Raipur  CHHATTISGARH

       ship-postal-code  ship-country  \
0              400081.0            IN
1              560085.0            IN
2              410210.0            IN
3              605008.0            IN
4              600073.0            IN
...                 ...           ...
128970         500013.0            IN
128971         122004.0            IN
128972         500049.0            IN
128973         389350.0            IN
128974         492014.0            IN

                                            promotion-ids    B2B  \
0                                                     NaN  False
1       Amazon PLCC Free-Financing Universal Merchant ...  False
2            IN Core Free Shipping 2015/04/08 23-48-5-108   True
3                                                     NaN  False
4                                                     NaN  False
...                                                   ...    ...
128970                                                NaN  False
128971       IN Core Free Shipping 2015/04/08 23-48-5-108  False
128972                                                NaN  False
128973       IN Core Free Shipping 2015/04/08 23-48-5-108  False
128974       IN Core Free Shipping 2015/04/08 23-48-5-108  False

        fulfilled-by Unnamed: 22
0          Easy Ship         NaN
1          Easy Ship         NaN
2                NaN         NaN
3          Easy Ship         NaN
4                NaN         NaN
...              ...         ...
128970           NaN       False
128971           NaN       False
128972           NaN       False
128973           NaN       False
128974           NaN       False

[128975 rows x 24 columns]>

In [36]:
df.isnull().sum().sort_values(ascending=False)

fulfilled-by          89698
promotion-ids         49153
Unnamed: 22           49050
currency               7795
Amount                 7795
Courier Status         6872
ship-country             33
ship-postal-code         33
ship-state               33
ship-city                33
ship-service-level        0
Style                     0
Date                      0
B2B                       0
Status                    0
Fulfilment                0
Sales Channel             0
Qty                       0
Order ID                  0
ASIN                      0
Size                      0
Category                  0
SKU                       0
index                     0
dtype: int64

In [38]:
df['Order ID'].duplicated().sum()

np.int64(8597)

In [37]:
df.duplicated().sum()

np.int64(0)

In [39]:
df.columns.tolist()

['index',
 'Order ID',
 'Date',
 'Status',
 'Fulfilment',
 'Sales Channel ',
 'ship-service-level',
 'Style',
 'SKU',
 'Category',
 'Size',
 'ASIN',
 'Courier Status',
 'Qty',
 'currency',
 'Amount',
 'ship-city',
 'ship-state',
 'ship-postal-code',
 'ship-country',
 'promotion-ids',
 'B2B',
 'fulfilled-by',
 'Unnamed: 22']

In [40]:
df = df.drop(columns=['index'])

In [41]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
    .str.replace('-', '_')
)

In [42]:
df.columns.tolist()

['order_id',
 'date',
 'status',
 'fulfilment',
 'sales_channel',
 'ship_service_level',
 'style',
 'sku',
 'category',
 'size',
 'asin',
 'courier_status',
 'qty',
 'currency',
 'amount',
 'ship_city',
 'ship_state',
 'ship_postal_code',
 'ship_country',
 'promotion_ids',
 'b2b',
 'fulfilled_by',
 'unnamed:_22']

In [43]:
df.isnull().sum().sort_values(ascending=False)

fulfilled_by          89698
promotion_ids         49153
unnamed:_22           49050
currency               7795
amount                 7795
courier_status         6872
ship_city                33
ship_country             33
ship_postal_code         33
ship_state               33
style                     0
status                    0
b2b                       0
fulfilment                0
sales_channel             0
sku                       0
ship_service_level        0
qty                       0
date                      0
asin                      0
size                      0
category                  0
order_id                  0
dtype: int64

In [44]:
df['fulfilled_by'].value_counts(dropna=False)

fulfilled_by
NaN          89698
Easy Ship    39277
Name: count, dtype: int64

In [45]:
pd.crosstab(
    df['fulfilment'],
    df['fulfilled_by'],
    dropna=False
)

fulfilled_by  Easy Ship    NaN
fulfilment
Amazon                0  89698
Merchant          39277      0

In [48]:
df['promotion_ids'].value_counts(dropna=False)

promotion_ids
NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        49153
IN Core Free Shipping 2015/04/08 23-48-5-108                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               46100
Duplicated A12RHGVGRWOT3S 1560498941486                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      489
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-G5ZRX4BZOIODU,Amazon PLCC Free-Financing Universal Merchant AAT-PZHUW6DZX4BPS,Amazon PLCC Free-Financing Universal Merchant AAT-XX7G3ZRJJJ5LG,Amazon PLCC Free-Financing Universal Merchant AAT-LEHCKNDBJG64E,Amazon PLCC Free-Financing Universal Merchant AAT-DJVHCEV7D7RQY,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                       458
Duplicated AYTJSBA8ZOP16 1567159860988                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       433
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ...
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-EWAPBB6BDRGM6,Amazon PLCC Free-Financing Universal Merchant AAT-R7GXNZWISTRFA,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-5ZEB2OGNZ32MC,Amazon PLCC Free-Financing Universal Merchant AAT-NT3ZJJGQ3JK3Q,Amazon PLCC Free-Financing Universal Merchant AAT-5SHH3G55USK5C,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                         1
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-EWAPBB6BDRGM6,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,VPC-44571-38708638 Coupon,Amazon PLCC Free-Financing Universal Merchant AAT-5ZEB2OGNZ32MC,Amazon PLCC Free-Financing Universal Merchant AAT-NT3ZJJGQ3JK3Q,Amazon PLCC Free-Financing Universal Merchant AAT-5SHH3G55USK5C,Amazon PLCC Free-Financing Universal Merchant AAT-TNYBHEAO7HOHO,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4,Amazon PLCC Free-Financing Universal Merchant AAT-QMFZ3M7T5NPDS,Amazon PLCC Free-Financing Universal Merchant #MP-pmilan-1601980554292        1
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-SL3Y2YRMAUNFC,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-EWAPBB6BDRGM6,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-5ZEB2OGNZ32MC,Amazon PLCC Free-Financing Universal Merchant AAT-NT3ZJJGQ3JK3Q,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                                                                                         1
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-SL3Y2YRMAUNFC,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-EWAPBB6BDRGM6,Amazon PLCC Free-Financing Universal Merchant AAT-R7GXNZWISTRFA,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-5ZEB2OGNZ32MC,Amazon PLCC Free-Financing Universal Merchant AAT-NT3ZJJGQ3JK3Q,Amazon PLCC Free-Financing Universal Merchant AAT-5SHH3G55USK5C,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                         1
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-EWAPBB6BDRGM6,Amazon PLCC Free-Financing Universal Merchant AAT-R7GXNZWISTRFA,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-NT3ZJJGQ3JK3Q,Amazon PLCC Free-Financing Universal Merchant AAT-5SHH3G55USK5C,Amazon PLCC Free-Financing Universal Merchant AAT-TNYBHEAO7HOHO,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4,Amazon PLCC Free-Financing Universal Merchant AAT-QMFZ3M7T5NPDS,Amazon PLCC Free-Financing Universal Merchant #MP-pmilan-1601980554292                                  1
Name: count, Length: 5788, dtype: int64

In [49]:
df['promotion_ids'] = df['promotion_ids'].fillna('no id')

In [47]:
df['fulfiled_by'] = df['fulfilled_by'].fillna('not applicable')

In [50]:
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

In [56]:
df['amount'].value_counts(dropna=False)

amount
NaN        7795
399.00     5442
771.00     2797
735.00     2436
0.00       2343
           ...
719.05        1
829.52        1
708.58        1
1244.00       1
639.00        1
Name: count, Length: 1411, dtype: int64

In [54]:
df['currency'] = df['currency'].fillna('INR')

In [57]:
df[df['amount'].isnull()]['status'].value_counts()

status
Cancelled                       7566
Shipped                          208
Shipped - Delivered to Buyer       8
Shipping                           8
Shipped - Returned to Seller       3
Pending                            2
Name: count, dtype: int64

In [59]:
df = df.dropna(subset=['amount'])

In [58]:
df['status'].value_counts()

status
Shipped                          77804
Shipped - Delivered to Buyer     28769
Cancelled                        18332
Shipped - Returned to Seller      1953
Shipped - Picked Up                973
Pending                            658
Pending - Waiting for Pick Up      281
Shipped - Returning to Seller      145
Shipped - Out for Delivery          35
Shipped - Rejected by Buyer         11
Shipping                             8
Shipped - Lost in Transit            5
Shipped - Damaged                    1
Name: count, dtype: int64

In [67]:
df['courier_status'].value_counts(dropna=False)

courier_status
Shipped      109487
Unshipped      6557
Cancelled      5136
Name: count, dtype: int64

In [66]:
df[df['courier_status'].isnull()]['status'].value_counts()

Series([], Name: count, dtype: int64)

In [65]:
df['courier_status']=df['courier_status'].fillna('Cancelled')

In [70]:
df[df['ship_city'].isnull()]['status'].value_counts()

status
Shipped                         16
Shipped - Delivered to Buyer     7
Cancelled                        5
Shipped - Returned to Seller     3
Name: count, dtype: int64

In [73]:

shipping_cols = ['ship_city', 'ship_country', 'ship_postal_code', 'ship_state']
df[shipping_cols] = df[shipping_cols].fillna('Unknown')

In [92]:
df.shape

(121180, 24)

In [75]:
df.dtypes

order_id                  str
date                      str
status                    str
fulfilment                str
sales_channel             str
ship_service_level        str
style                     str
sku                       str
category                  str
size                      str
asin                      str
courier_status            str
qty                     int64
currency                  str
amount                float64
ship_city                 str
ship_state                str
ship_postal_code       object
ship_country              str
promotion_ids             str
b2b                      bool
fulfilled_by              str
unnamed:_22            object
fulfiled_by               str
dtype: object

In [93]:
df['date'] = pd.to_datetime(df['date'])

In [95]:
df['date'].dtype

dtype('<M8[ns]')

In [94]:
df['date'].sample(5)

64993   2022-05-19
28492   2022-04-13
5439    2022-04-27
20811   2022-04-18
37760   2022-04-08
Name: date, dtype: datetime64[ns]

In [96]:
df['date'] = df['date'].astype('datetime64[ns]')

In [85]:
%pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [97]:
df.to_excel('cleaned.xlsx', index=False)

In [87]:
import pymysql
from sqlalchemy import create_engine

In [90]:
engine_mysql = create_engine("mysql+pymysql://root:Saumyajain_16@localhost:3306/amazon_sales")
try :
    engine_mysql
    print("connected")
except:
    print("not connected")

connected

In [91]:
df.to_sql(name = "amazon",con=engine_mysql,if_exists='replace',index=False)

121180

In [27]:
df.columns = df.columns.str.strip()

In [25]:
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

In [29]:
print("Unique Orders:", df['Order ID'].nunique())

Unique Orders: 17993

In [20]:
%pip install sqlalchemy

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.52-cp314-cp314-macosx_11_0_arm64.whl.metadata (9.6 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in /Users/saumyajain/.conda/envs/jupyterlab-env/lib/python3.14/site-packages (from sqlalchemy) (4.16.0)
Downloading sqlalchemy-2.0.52-cp314-cp314-macosx_11_0_arm64.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 15.8 MB/s  0:00:00
Installing collected packages: sqlalchemy
Successfully installed sqlalchemy-2.0.52
Note: you may need to restart the kernel to use updated packages.